# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{node.rb}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Colin MacKenzie IV"]
  s.date = %q{2010-09-01}
  s.default_executable = %q{node-rb}
  s.description = %q{Embeds a Ruby interpreter (www.ruby-lang.org) into Node.js (www.nodejs.org) for your coding pleasure.}
  s.email = %q{sinisterchipmunk@gmail.com}
  s.executables = ["node-rb"]
  s.extensions = ["ext/ruby/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/node-rb",
     "ext/ruby/extconf.h",
     "ext/ruby/extconf.rb",
     "ext/ruby/node/common.h",
     "ext/ruby/node/node_wrapper.cpp",
     "ext/ruby/node/ruby.cpp",
     "ext/ruby/node/ruby18.cpp",
     "ext/ruby/node/ruby19.cpp",
     "ext/ruby/ruby/ruby.cpp",
     "ext/ruby/wscript.rb.erb",
     "lib/node.rb",
     "lib/node.rb.rb",
     "lib/node_rb.rb",
     "spec/lib/noderb_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/nodes/context.js"
  ]
  s.homepage = %q{http://github.com/sinisterchipmunk/node.rb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Embeds a Ruby interpreter (www.ruby-lang.org) into Node.js (www.nodejs.org) for your coding pleasure.}
  s.test_files = [
    "spec/lib/noderb_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

